package Visual;
import Entidades.HistoriaClinica;
import Entidades.DetalleHistoria;
import static Visual.MedicoVisual.listMedico;
import static Visual.PacienteVisual.listPaciente;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

public class AtencionPaciente extends javax.swing.JFrame {
    
    public static HistoriaClinica historia =null;
    public static DetalleHistoria dh=null;
    GregorianCalendar c=new GregorianCalendar();
    
    public AtencionPaciente() {
        initComponents();
        BotonTransparente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHistorialPaciente = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabelTipoDeSangre = new javax.swing.JLabel();
        jLabelObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObservaciones = new javax.swing.JTextArea();
        jLabelFechAper = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelCedMedico = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelCed = new javax.swing.JLabel();
        jLabelTipSan = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelHistorialPaciente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelHistorialPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHistorialPaciente.setText("Historial del Paciente");
        getContentPane().add(jLabelHistorialPaciente);
        jLabelHistorialPaciente.setBounds(0, 60, 840, 29);

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(30, 110, 130, 30);

        jLabelCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCedula.setText("Cedula:");
        getContentPane().add(jLabelCedula);
        jLabelCedula.setBounds(30, 150, 130, 30);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButtonGuardar.setToolTipText("Guardar");
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar);
        jButtonGuardar.setBounds(220, 260, 60, 50);

        jLabelTipoDeSangre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTipoDeSangre.setText("Tipo de Sangre:");
        getContentPane().add(jLabelTipoDeSangre);
        jLabelTipoDeSangre.setBounds(30, 190, 126, 30);

        jLabelObservaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelObservaciones.setText("Observaciones:");
        getContentPane().add(jLabelObservaciones);
        jLabelObservaciones.setBounds(390, 110, 119, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha De Atencion", "Nombre del Medico", "Especialidad", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 310, 840, 90);

        jTextAreaObservaciones.setColumns(20);
        jTextAreaObservaciones.setRows(5);
        jScrollPane2.setViewportView(jTextAreaObservaciones);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 150, 350, 110);

        jLabelFechAper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFechAper.setText("Fecha Apertura:");
        getContentPane().add(jLabelFechAper);
        jLabelFechAper.setBounds(30, 230, 130, 30);

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButtonRegresar.setToolTipText("Regresar");
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar);
        jButtonRegresar.setBounds(540, 260, 60, 50);

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButtonSalir.setToolTipText("Salir");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(760, 10, 70, 70);
        getContentPane().add(jLabelCedMedico);
        jLabelCedMedico.setBounds(10, 10, 90, 30);
        getContentPane().add(jLabelNom);
        jLabelNom.setBounds(170, 110, 160, 30);
        getContentPane().add(jLabelCed);
        jLabelCed.setBounds(170, 150, 160, 30);
        getContentPane().add(jLabelTipSan);
        jLabelTipSan.setBounds(170, 190, 160, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(200, 230, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/internalframe.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 400);

        setSize(new java.awt.Dimension(841, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        if(!"".equals(jTextAreaObservaciones.getText())){
        GregorianCalendar gc=new GregorianCalendar();
        dh=new DetalleHistoria(gc, jTextAreaObservaciones.getText(),listMedico.get(MedicoVisual.buscar_cedula(jLabelCedMedico.getText())));
        historia=new HistoriaClinica((GregorianCalendar) jDateChooser1.getCalendar());
        listPaciente.get(PacienteVisual.buscar_cedula(jLabelCed.getText())).getHistClinica().setDetalleHistoria(dh);
        mostrarAtencion();
        limpiar();
        System.out.println("Paciente despues de guardar");
        System.out.println(""+listPaciente.get(PacienteVisual.buscar_cedula(jLabelCed.getText())).toString());
        }else{
            JOptionPane.showMessageDialog(null, "No deben haber campos vacios");
        }
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        Bienvenida bv=new Bienvenida();
        bv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        int dialog=JOptionPane.YES_NO_OPTION;
        int result=JOptionPane.showConfirmDialog(null,"Desea salir del programa?","Salir",dialog);
        if(result==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed
    public void mostrarAtencion(){
        
        try{
            String matrix[][]=new String[listPaciente.get(PacienteVisual.buscar_cedula(jLabelCed.getText())).getHistClinica().getDetalleHistoria().size()][4];
            for (int i = 0; i < listPaciente.get(PacienteVisual.buscar_cedula(jLabelCed.getText())).getHistClinica().getDetalleHistoria().size(); i++) {
                matrix[i][0]=listPaciente.get(PacienteVisual.buscar_cedula(jLabelCed.getText())).getHistClinica().getDetalleHistoria().get(i).getFechaString();
                matrix[i][1]=listPaciente.get(PacienteVisual.buscar_cedula(jLabelCed.getText())).getHistClinica().getDetalleHistoria().get(i).getListMed().getNombre();
                matrix[i][2]=listPaciente.get(PacienteVisual.buscar_cedula(jLabelCed.getText())).getHistClinica().getDetalleHistoria().get(i).getListMed().getEspecialidad();
                matrix[i][3]=listPaciente.get(PacienteVisual.buscar_cedula(jLabelCed.getText())).getHistClinica().getDetalleHistoria().get(i).getObservacion();
                         
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                "Fecha De Atencion", "Nombre del Medico", "Especialidad", "Observaciones"
            }
        ));
            
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null,"La tabla esta vacia");
        }    
            
            
        }
    private void BotonTransparente(){
            jButtonGuardar.setOpaque(false);
            jButtonGuardar.setContentAreaFilled(false);
            jButtonGuardar.setBorderPainted(false);
            jButtonRegresar.setOpaque(false);
            jButtonRegresar.setContentAreaFilled(false);
            jButtonRegresar.setBorderPainted(false);
            jButtonSalir.setOpaque(false);
            jButtonSalir.setContentAreaFilled(false);
            jButtonSalir.setBorderPainted(false);
        }
    public void limpiar(){
        jTextAreaObservaciones.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtencionPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtencionPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtencionPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtencionPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtencionPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JButton jButtonRegresar;
    public static javax.swing.JButton jButtonSalir;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabelCed;
    public static javax.swing.JLabel jLabelCedMedico;
    public static javax.swing.JLabel jLabelCedula;
    public static javax.swing.JLabel jLabelFechAper;
    public static javax.swing.JLabel jLabelHistorialPaciente;
    public static javax.swing.JLabel jLabelNom;
    public static javax.swing.JLabel jLabelNombre;
    public static javax.swing.JLabel jLabelObservaciones;
    public static javax.swing.JLabel jLabelTipSan;
    public static javax.swing.JLabel jLabelTipoDeSangre;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextArea jTextAreaObservaciones;
    // End of variables declaration//GEN-END:variables
}
