package Visual;

import javax.swing.JOptionPane;

public class Bienvenida extends javax.swing.JFrame {

    public Bienvenida() {
        initComponents();
        BotonTransparente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdministrar = new javax.swing.JButton();
        jButtonAtencion = new javax.swing.JButton();
        jLabelBienvenido = new javax.swing.JLabel();
        jLabelElija = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrar.png"))); // NOI18N
        jButtonAdministrar.setText("Administrar");
        jButtonAdministrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdministrar);
        jButtonAdministrar.setBounds(160, 270, 180, 70);

        jButtonAtencion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atencionMedica.png"))); // NOI18N
        jButtonAtencion.setText("Atencion");
        jButtonAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtencionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtencion);
        jButtonAtencion.setBounds(430, 270, 180, 70);

        jLabelBienvenido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenido.setText("Bienvenido Al Sistema De Gestion Hospitalario ");
        getContentPane().add(jLabelBienvenido);
        jLabelBienvenido.setBounds(110, 130, 560, 40);

        jLabelElija.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelElija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelElija.setText("Elija una de las opciones");
        getContentPane().add(jLabelElija);
        jLabelElija.setBounds(300, 210, 150, 17);

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButtonSalir.setToolTipText("Salir");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(710, 10, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/internalframe.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 440);

        setSize(new java.awt.Dimension(792, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarActionPerformed
        Login lg=new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAdministrarActionPerformed

    private void jButtonAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtencionActionPerformed
        Medicocedula mc=new Medicocedula();
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAtencionActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        int dialog=JOptionPane.YES_NO_OPTION;
        int result=JOptionPane.showConfirmDialog(null,"Desea salir del programa?","Salir",dialog);
        if(result==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed
    private void BotonTransparente(){
            jButtonSalir.setOpaque(false);
            jButtonSalir.setContentAreaFilled(false);
            jButtonSalir.setBorderPainted(false);
            jButtonAdministrar.setOpaque(false);
            jButtonAdministrar.setContentAreaFilled(false);
            jButtonAdministrar.setBorderPainted(false);
            jButtonAtencion.setOpaque(false);
            jButtonAtencion.setContentAreaFilled(false);
            jButtonAtencion.setBorderPainted(false);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministrar;
    private javax.swing.JButton jButtonAtencion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelElija;
    // End of variables declaration//GEN-END:variables
}
