package Visual;

import javax.swing.JOptionPane;
import static Visual.MedicoVisual.listMedico;
public class Medicocedula extends javax.swing.JFrame {
    MedicoVisual mv=new MedicoVisual();
    public static String cedula;
    public Medicocedula() {
        initComponents();
        BotonTransparente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBusqueda = new javax.swing.JLabel();
        jLabelIngrese = new javax.swing.JLabel();
        jTextFieldingrese = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBusqueda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusqueda.setText("Ingreso del Medico");
        getContentPane().add(jLabelBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, -1));

        jLabelIngrese.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIngrese.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIngrese.setText("Ingrese su cedula:");
        getContentPane().add(jLabelIngrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 420, -1));

        jTextFieldingrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldingreseActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldingrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 300, -1));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupita.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 140, -1));

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 140, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/doctor (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/internalframe.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        setSize(new java.awt.Dimension(673, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldingreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldingreseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldingreseActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        Bienvenida bv=new Bienvenida();
        bv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if(mv.buscar_cedula(jTextFieldingrese.getText())!=-1){
            cedula=listMedico.get(mv.buscar_cedula(jTextFieldingrese.getText())).getCedula();
            BusquedaPaciente bp=new BusquedaPaciente();
            JOptionPane.showMessageDialog(null, "Se encontro al Medico");
            bp.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No se encotro al Medico");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    
    private void BotonTransparente(){
            jButtonBuscar.setOpaque(false);
            jButtonBuscar.setContentAreaFilled(false);
            jButtonBuscar.setBorderPainted(false);
            jButtonRegresar.setOpaque(false);
            jButtonRegresar.setContentAreaFilled(false);
            jButtonRegresar.setBorderPainted(false);
            
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicocedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicocedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicocedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicocedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicocedula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBusqueda;
    private javax.swing.JLabel jLabelIngrese;
    private javax.swing.JTextField jTextFieldingrese;
    // End of variables declaration//GEN-END:variables

    
}
