package Visual;

import javax.swing.JOptionPane;

public class PrincipalJFrame extends javax.swing.JFrame {

    
    
    public PrincipalJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        BotonTransparente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPaciente = new javax.swing.JButton();
        jButtonMedico = new javax.swing.JButton();
        jButtonregresar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelRp = new javax.swing.JLabel();
        jLabelRm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/paciente (2).png"))); // NOI18N
        jButtonPaciente.setToolTipText("Registro Pacientes");
        jButtonPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPaciente);
        jButtonPaciente.setBounds(130, 100, 250, 260);

        jButtonMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/doctor (2).png"))); // NOI18N
        jButtonMedico.setToolTipText("Registro Medicos");
        jButtonMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMedico);
        jButtonMedico.setBounds(540, 100, 250, 260);

        jButtonregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButtonregresar.setToolTipText("Regresar");
        jButtonregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonregresar);
        jButtonregresar.setBounds(840, 410, 60, 50);

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButtonSalir.setToolTipText("Salir");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(840, 10, 70, 70);

        jLabelRp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRp.setText("Registro Paciente");
        getContentPane().add(jLabelRp);
        jLabelRp.setBounds(130, 370, 250, 30);

        jLabelRm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRm.setText("Registro Medico");
        getContentPane().add(jLabelRm);
        jLabelRm.setBounds(540, 370, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/internalframe.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setMaximumSize(new java.awt.Dimension(338, 168));
        jLabel1.setPreferredSize(new java.awt.Dimension(338, 168));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 494);

        setSize(new java.awt.Dimension(921, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        PacienteVisual pv=new PacienteVisual();
        pv.setVisible(true);
        pv.mostrarPaciente();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicoActionPerformed
        MedicoVisual mv=new MedicoVisual();
        mv.setVisible(true);
        mv.mostrar();
        this.dispose();
    }//GEN-LAST:event_jButtonMedicoActionPerformed

    private void jButtonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregresarActionPerformed
        Bienvenida bv=new Bienvenida();
        bv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonregresarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        int dialog=JOptionPane.YES_NO_OPTION;
        int result=JOptionPane.showConfirmDialog(null,"Desea salir del programa?","Salir",dialog);
        if(result==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /*
       Metodos
    */
    private void BotonTransparente(){
            jButtonMedico.setOpaque(false);
            jButtonMedico.setContentAreaFilled(false);
            jButtonMedico.setBorderPainted(false);
            jButtonPaciente.setOpaque(false);
            jButtonPaciente.setContentAreaFilled(false);
            jButtonPaciente.setBorderPainted(false);
            jButtonregresar.setBorderPainted(false);
            jButtonregresar.setOpaque(false);
            jButtonregresar.setContentAreaFilled(false);
            jButtonSalir.setBorderPainted(false);
            jButtonSalir.setOpaque(false);
            jButtonSalir.setContentAreaFilled(false);
            
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMedico;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRm;
    private javax.swing.JLabel jLabelRp;
    // End of variables declaration//GEN-END:variables
}
